= Parameters

The parent key for all of the following parameters is `openshift4_networking`.


== `namespace`

[horizontal]
type:: string
default:: `openshift-networking`

The namespace in which to deploy this component.


== `defaultNodeSelector`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
node-role.kubernetes.io/infra: ''
----

Node selector for the non-DaemonSet OpenShift networking workloads.

== `monitoring`

This parameter allows users to enable the component's monitoring configuration.
Currently the component has support for deploying custom `ServiceMonitors` on clusters which use component `prometheus` to manage a custom monitoring stack.

The component also deploys a `NetworkPolicy` to allow the independent monitoring stack to access the `openshift-network-diagnostics` metrics.

=== `enabled`

[horizontal]
type:: boolean
default:: `true`

Whether to deploy monitoring configurations.
If this parameter is set to `true`, the component will check whether component `prometheus` is present on the cluster.
If the component is missing, no configurations will be deployed regardless of the value of this parameter.

=== `instance`

[horizontal]
type:: string
default:: `null`

This parameter can be used to indicate which custom Prometheus instance should pick up the configurations managed by the component.

If the parameter is set to `null`, the default instance configured for component `prometheus` will be used.

=== `enableServiceMonitors`

[horizontal]
type:: dictionary
default:: https://github.com/appuio/component-openshift4-networking/blob/master/class/defaults.yml[See `class/defaults.yml`]

A dictionary with the names of service monitors as keys and booleans as the value.
Can be used to selectively enable or disable service monitors.

== `patches`

[horizontal]
type:: dictionary
default:: https://github.com/appuio/component-openshift4-networking/blob/master/class/defaults.yml[See `class/defaults.yml`]

Defines the patches to apply to the OpenShift networking components.
Patches can be removed in the hierarchy by setting the value to `null`.

The schema is defined as follows:
[source,yaml]
----
ip-reconciler: <1>
  target: <2>
    kind: CronJob
    apiVersion: batch/v1
    name: ip-reconciler
    namespace: openshift-multus
  patch: <3>
    spec:
      jobTemplate:
        spec:
          template:
            spec:
              nodeSelector: ${openshift4_networking:defaultNodeSelector}
----
<1> Name in hierarchy
<2> Object the patch is applied to. Consists of kind, apiVersion, name, and optionally namespace.
<3> Patch to apply
